version: "3.7"
services:

  web:
    build: ./mars
    command: gunicorn mars.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./mars/:/usr/src/mars/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    volumes:
      - ./mars/:/usr/src/mars/
    # externalport:internalport
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
